version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8834
      POSTGRES_DB: bizinsight
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  backend:
    image: maven:3.9-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./backend:/app
      - maven_cache:/root/.m2
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - db
      - ml-service

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    # Ensure vite binds to 0.0.0.0 to be accessible outside the container
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
  maven_cache:
