server.port=8080
spring.datasource.url=jdbc:postgresql://db:5432/bizinsight
spring.datasource.username=postgres
spring.datasource.password=8834
spring.jpa.hibernate.ddl-auto=update
ml.service.url=http://ml-service:8000
